# Load config only if not already loaded (e.g., when used as a module)
import sys
import os

if not config:  # config is empty when run standalone
    if "--configfile" in sys.argv:
        i = sys.argv.index("--configfile")
        config_path = sys.argv[i + 1]
        configfile: config_path
    else:
        config_path = "config/config.yaml"
        configfile: config_path

DATA_DIR = config["DATA_DIR"]
LOG_DIR = config["LOG_DIR"]
LOG_LEVEL = config["LOG_LEVEL"]
RIBONN_DATASETS = config["RIBONN_DATASETS"]
HCT116_ISOFORMS = config["HCT116_ISOFORMS"]

include: "rules/RiboNN_data.smk"

rule all:
    input: 
        expand(os.path.join(DATA_DIR, "RiboNN_{dataset}.csv"), dataset=RIBONN_DATASETS.keys()) +
        os.path.join(DATA_DIR, "HCT116_isoforms.csv")


rule prepare_HCT116_isoforms:
    input:
        gtf=HCT116_ISOFORMS['gtf'],
        fasta=HCT116_ISOFORMS['fasta'],
        logTE=HCT116_ISOFORMS['logTE']
    output:
        os.path.join(DATA_DIR, "HCT116_isoforms.csv")
    params:
        emit_utrs_without_cds=HCT116_ISOFORMS['emit_utrs_without_cds'],
        filter_protein_coding=HCT116_ISOFORMS['filter_protein_coding'],
        ribo_tpm_threshold=HCT116_ISOFORMS['ribo_tpm_threshold'],
        log_level=LOG_LEVEL
    conda:
        "envs/HCT116.yaml"
    log:
        os.path.join(LOG_DIR, "prepare_HCT116_isoforms.log")
    script:
        "scripts/prepare_HCT116_isoforms.py"
