# Load config
if "--configfile" in sys.argv:
    i = sys.argv.index("--configfile")
    config_path = sys.argv[i + 1]
    configfile: config_path
else:
    config_path = "config/config.yaml"
    configfile: config_path

DATA_DIR = config["DATA_DIR"]
LOG_DIR = config["LOG_DIR"]
DATASETS = config["DATASETS"]

include: "rules/RiboNN_data.smk"

rule all:
    input: 
        expand(os.path.join(DATA_DIR, "{dataset}.csv"), dataset=DATASETS.keys())