DATA_DIR: "data"
LOG_DIR: "logs"
LOG_LEVEL: "INFO"

RIBONN_DATASETS:
  Human:
    url: https://static-content.springer.com/esm/art%3A10.1038%2Fs41587-025-02712-x/MediaObjects/41587_2025_2712_MOESM3_ESM.xlsx
    sheet_name: "Human"
    add_seqs: True
  Mouse:
    url: https://static-content.springer.com/esm/art%3A10.1038%2Fs41587-025-02712-x/MediaObjects/41587_2025_2712_MOESM4_ESM.xlsx
    sheet_name: "Mouse"
    add_seqs: True

HCT116_ISOFORMS:
  gtf: resources/HCT116_Txome_WT.v1.1_nonAUG.sort.1TxPerGene_collapsed.gtf
  fasta: resources/HCT116_Txome_WT.v1.1_nonAUG.sort.1TxPerGene_collapsed.fa
  emit_utrs_without_cds: False
  filter_protein_coding: True

HCT116_ISOFORMS_TE:
  logTE: "resources/20260324-eif-master.csv"
  ribo_tpm_threshold: 5 # Filter out isoforms with ribo_tpm_minus < 5 in any of the replicates for a given condition and timepoint
  conditions:
    - "eif4e"
    - "eif3d"
    - "eif4g1"
    - "eif4g2"
    - "eif4g3"
  timepoints:
    - "4h"
    - "8h"

MIRNA_TARGETS:
  url: "https://www.targetscan.org/vert_80/vert_80_data_download/Summary_Counts.default_predictions.txt.zip"
  species_id: 9606  # Human
  score_columns:
    conserved_sites: "Total num conserved sites"
    context_score: "Total context++ score"
    weighted_context_score: "Cumulative weighted context++ score"

UORF_SOURCE:
  url: "https://static-content.springer.com/esm/art%3A10.1038%2Fs41587-022-01369-0/MediaObjects/41587_2022_1369_MOESM2_ESM.xlsx"
  excel_path: "resources/41587_2022_1369_MOESM2_ESM.xlsx"